### ISSUE TITLE
Analysis

### ISSUE THREAD

**Issue by lbrndnr** [lbrndnr/summaries-b15#1]
Ich hab so den grössten teil der Analysis Zusammenfassung geschrieben. Wär geil wenn jemand, der die Zusammenfassung auch gebrauchen will, den Rest noch machen könnte.

Hier ist so das wichtigste, was noch zusammengefasst werden müsste:
- [x] Konvergenz
- [x] Stetigkeit
- [x] Potenzreihen
- [ ] Existenz von Lösungen
- [x] Integral über Gebiete
- [ ] Oberflächenintegrale
- [x] Kritische Punkte/ Kurvendiskussion

Ich denke, die meisten Punkte sind schnell zusammengefasst.

Was meint ihr? Würde das noch jemand übernehmen?

**Comment by pavellunin** [comment]
Am 15. Juni 2016 um 10:35 schrieb Laurin Brandner notifications@github.com
:
